// <auto-generated />
namespace ProductionWIP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class _2303201501 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2303201501));
        
        string IMigrationMetadata.Id
        {
            get { return "201503240308260_2303201501"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
