// <auto-generated />
namespace ProductionWIP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class _2015040101 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2015040101));
        
        string IMigrationMetadata.Id
        {
            get { return "201504011852559_2015040101"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
